[package]
name = "rust_module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_module"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.18.1"
reed-solomon-erasure = "4.0"
reed-solomon = "0.2.1"
